services:
  db:
    image: postgres:latest
    container_name: hyprtrain_db
    restart: always
    environment:
      POSTGRES_DB: hyprtrain_dev
      POSTGRES_USER: hyprtrain
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/src/db/init:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    working_dir: /usr/src/app
    env_file:
      - ./server/.env
    depends_on:
      - db
    
volumes:
  pgdata: